### ISSUE TITLE
support .bash_history format

### ISSUE THREAD

**Issue by aspiers** [abel-navarro/logmerge#2]
`.bash_history` stores timestamped commands if `HISTTIMEFORMAT` is set, which it seems to be by default on SLES.  Would be very useful to merge these lines in.

**Comment by AbelNavarro** [comment]
@aspiers thanks for the feedback. The `HISTTIMEFORMAT` variable allows for a [myriad of formats](http://man7.org/linux/man-pages/man3/strftime.3.html). I don't think this program is flexible enough to tackle that. Instead, it would be possible to parse `HISTTIMEFORMAT` as is defined by default in SUSE distributions. That would be `"%F %H:%M:%S "`, which produces lines like `357  2016-11-18 09:47:46 history`. Would that suffice?

**Comment by aspiers** [comment]
@abel-navarro There is no problem here because if `.bash_history` contains timestamps, they are always in seconds since the UNIX epoch. `HISTTIMEFORMAT` determines:
1. whether epoch timestamps are written to `.bash_history`
2. the format of the output from running `history` interactively

It does not affect the format of timestamps written to `.bash_history`.
